### PR TITLE
Fix issue 477

### LINKED ISSUE #477: Keeping directory structure in `shared_data`?
Current implementation flattens/removes directory structure and stores data in one place. Does it require to keep the directory structure?

Example:
```
appman.shared_data = ["pdbs/adk-123.pdb", "examples/adk-123.pdb"]
-> uploads files to
staging_area/adk-123.pdb
```

### PR DESCRIPTION
**Pull request by iparask**
Hello, 

this PR fixes #477. It resolves any `shared_data` directive based on a `>` exists or not and pushes them to the pilot via pilot's `stage_in` method.

This is unit tested as well.

### CODE REVIEW

**Comment by lee212** [comment]
Are these affected?
https://github.com/radical-cybertools/radical.entk/blob/b266c754d6cca1443f87cc39ed11d7b77f580993/src/radical/entk/execman/rp/task_processor.py#L474-L475

**Comment by iparask** [comment]
You mean because of `$SHARED`. Thank you! I'll check and get back to you

**Comment by iparask** [comment]
Your comment made me think how placeholders are resolved when there are in both sides of `>`. This triggered some extra changes.

However, the user needs to keep in mind that EnTK does not have any knowledge of folder structure under `$SHARED`. For example, a user sets `shared_data` as:

```python
appman.shared_data = ['folder1/file1 > folder1/file1']
```
and want to use `file` as input staging for a task. The task definition has to include the folder tree after `$SHARED`:
```python
td.input_staging = ['$SHARED/folder1/file1']
```

**Comment by iparask** [comment]
ping @lee212

**Review by andre-merzky — APPROVED** [review]
LGTM

**Pull request merged**
