### PR TITLE
Compatibility/exec

### PR DESCRIPTION
**Pull request by andre-merzky**
This PR reroutes the `from_dict` type checks to the setter type checks for the executable, thus fixing #322.

### CODE REVIEW

**Comment by andre-merzky** [comment]
PS.: this contains commits from master, too - as soon as master is merged back into devel, this PR will become much smaller.

**Comment by mturilli** [comment]
@andre-merzky, the error in Codacy is a false positive. Could you reformat so to avoid it? I was unable to understand why Travis complains, all the tests seem to pass. Any idea?

**Comment by andre-merzky** [comment]
I don't see the codacy output - when I follow the link, it tells me that the branch is not covered.  If you see the message, can you paste it please?

The travis tests seem to hang - Vivek says that this happens now and then, and he just reruns them.  I am not sure I agree with that approach, but that's for another time to discuss ;-)

**Comment by andre-merzky** [comment]
Pfft, systems...  I see it now.

That part of code wasn't really touched by my PR - it will disappear once the devel branch is synced with master.

**Pull request merged**
