### PR TITLE
move to relative imports, simplify code hierarchy

### LINKED ISSUE #312: src tree
Several subdirs in the EnTK source tree have only one file each, specifically `pipeline/`, `stage/`, and `task/`.  Why is that?  Wouldn't it make sense to move those files one level up, to simplify navigation?

### PR DESCRIPTION
**Pull request by andre-merzky**
This fixes #312

### CODE REVIEW

**Comment by mturilli** [comment]
@andre-merzky see https://travis-ci.com/github/radical-cybertools/radical.entk/jobs/445921451

**Comment by andre-merzky** [comment]
> @andre-merzky see https://travis-ci.com/github/radical-cybertools/radical.entk/jobs/445921451

Yeah, I was waiting for travis to tell me to where to fix the tests :-)  Will do.

**Comment by iparask** [comment]
The tests pass. Travis fails because pylint tries to lint removed files, those that moved around. I think this PR is fine. Let me run a quick check to make sure everything is okay and I would say let's merge. @andre-merzky, @mturilli do you agree?

**Review by iparask — APPROVED** [review]
Looks good to me

**Pull request merged**
