### PR TITLE
implement long uids

### PR DESCRIPTION
**Pull request by andre-merzky**
This addresses #306:

```
...
Update: pipeline.0009.stage.0029.task.0029 state: DEQUEUED
Update: pipeline.0009.stage.0029.task.0029 state: DONE
Update: pipeline.0009.stage.0029 state: DONE
Update: pipeline.0009 state: DONE
...
...

### CODE REVIEW

**Comment by vivek-bala** [comment]
LGTM! I just rebased it towards devel (from master). Let me know if you wanted to move back to master (hotfix?).

**Comment by andre-merzky** [comment]
@mturilli , @vivek-bala : So whats the merge policy on failing tests?

**Comment by mturilli** [comment]
No merge with failure?

**Comment by vivek-bala** [comment]
We rerun the tests till they pass :P

On a serious note, sometimes 1-2 tests fail because they don't get the expected state for a Task or the resource. This was the reason why initially the test failed for this PR. The solution so far has been to rerun the test suite (can be done directly on Travis).

If the test fails because of other errors (which can be seen by looking at the test results on Travis), I think we make the appropriate code changes or test changes to fix the failure and push back to the same PR.

**Comment by andre-merzky** [comment]
So why do the tests fail sometimes?   Doesn't that defeat the purpose of running tests (a little)? ;-)

**Comment by vivek-bala** [comment]
I should have phrased it better. What I have seen is that sometimes pilot doesn't report its final state when run on localhost. I agree there should be a test for that as well, but I think that would go in RP rather than here. Put in another way, I think that would be an RP test rather an EnTK-RP integration test. What do you think?

I should also say that I don't know how to reproduce the error consistently though.

**Comment by andre-merzky** [comment]
Underdtood, thanks  Vivek!

**Pull request merged**
