### PR TITLE
inform RE about RP level task errors

### PR DESCRIPTION
**Pull request by andre-merzky**
This PR forwards exception information from RP to RE and let's RP report them.  This works sometimes.  ARGH!  I don't see how on some runs all tasks get the exception information, and on other identical runs they don't.  The RP layer reporting is the same every time - but somehow the RMQ state update messages sometimes are out of order, and old updates overwrite the setting of new ones.  What a mess...

### CODE REVIEW

**Comment by mturilli** [comment]
This needs to be investigated and understood. We need to find a solution that, at the moment, we don't yet know. Sprint 20221223 will be used to understand the solution. If viable, to implement it too.

**Comment by andre-merzky** [comment]
This is now ready for review.  The PR is a bit larger than the semantic changes warrant, but the added (and commented for now) log messages and the light refactoring make it easier to trace the task updates throughout the code.

**Comment by mturilli** [comment]
Review will be long as it is a major PR.

**Review by mtitov — APPROVED** [review]
LGTM! 
and would suggest to remove commented lines used for debug (not used logging calls)

**Comment by andre-merzky** [comment]
> would suggest to remove commented lines used for debug (not used logging calls)

I removed them now.  It took me a long while to understand the path of the task update messages, and those logs helped but were too verbose to leave active.  But we have them in git for the next time :-D

**Pull request merged**
