### PR TITLE
Devel nodb 2

### PR DESCRIPTION
**Pull request by mtitov**

### CODE REVIEW

**Comment by mtitov** [comment]
FIXME: after session is finished, the result file `tmgr.0000.json` doesn't contain info about tasks

**Review by mturilli — APPROVED** [review]
As discussed, I agree it is not pretty but as it works, I think for now we can merge it.

**Comment by mturilli** [comment]
Looking at the tests, should we rapidly address the obsolete keys? Also, following what discussed for RP, should we enable profiles by default?

**Comment by mtitov** [comment]
> Looking at the tests, should we rapidly address the obsolete keys?

@mturilli this tests fail due to having RU,RP-devel branches without NoDB, that will be resolved after merging RU and RP into devel (will have some delay in merging EnTK, thus to confirm that tests pass)

> Also, following what discussed for RP, should we enable profiles by default?

it is enabled by default now

**Pull request merged**
