### PR TITLE
Fix/examples 

### PR DESCRIPTION
**Pull request by jdakka**
changed task executables from list to str for examples scripts

### CODE REVIEW

**Comment by andre-merzky** [comment]
Hey Jumana -  thanks for that!  But why was it closed?  Master does not yet have string execs - but that only means that the PR has to wait for a bit... :-)

**Comment by vivek-bala** [comment]
Same here. @jdakka any particular why this PR was closed? #318 seems very similar to this one.

**Comment by jdakka** [comment]
@vivek-bala Because you asked me to push to `devel` not `master`

**Comment by vivek-bala** [comment]
Oh! I see. Thanks. You can use the edit button on the top right of the PR to change the target branch :)

**Comment by jdakka** [comment]
nifty :)

**Pull request closed without merging**
