### PR TITLE
Fix/issue 393

### PR DESCRIPTION
**Pull request by iparask**
It fixes issue #393.

### CODE REVIEW

**Comment by iparask** [comment]
The last commit adds a `umgr.close()` command in the task manager. With this everything terminated correctly.

**Comment by lee212** [comment]
I just ran a test run on Summit which wasn't closed.

```
  python               : 3.7.0
  pythonpath           : /sw/summit/xalt/1.1.4/site:/sw/summit/xalt/1.1.4/libexec
  virtualenv           : /ccs/home/hrlee/venv3/entk.copy2

  radical.entk         : 0.90.0-v0.72.0-63-ga35a2d4@feature-proc_mgmt
  radical.pilot        : 0.90.6-v0.90.1-157-g4f05a4f@devel
  radical.saga         : 0.90.6-bv0.72.1-67-g5deb253@devel
  radical.utils        : 0.90.6-v0.90.3-168-gd27dc3a@devel
```

**Comment by iparask** [comment]
@lee212 can you put the log output in the ticket?

**Comment by lee212** [comment]
Not sure which file would be interested in but here are some of them from the session:

STDOUT:
```
EnTK session: re.session.login2.hrlee.018242.0032
Creating AppManagerSetting up RabbitMQ system                                 ok
                                                                              ok
Validating and assigning resource manager                                     ok
Setting up RabbitMQ system                                                   n/a
new session: [re.session.login2.hrlee.018242.0032]                             \
database   : [mongodb://rct:rct_test@two.radical-project.org/rct_test]        ok
create pilot manager                                                          ok
submit 1 pilot(s)
        [ornl.summit:1]
                                                                              ok
All components created
Update: pipeline.0000 state: SCHEDULING
Update: pipeline.0000.stage.0000 state: SCHEDULING
Update: pipeline.0000.stage.0000.my-first-task state: SCHEDULING
Update: pipeline.0000.stage.0000.my-first-task state: SCHEDULED
Update: pipeline.0000.stage.0000 state: SCHEDULED
create unit manager/ccs/home/hrlee/venv3/entk.copy2/lib/python3.7/site-packages/pymongo/topology.py:155: UserWarning: MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: http://api.mongodb.org/python/current/faq.html#is-pymongo-fork-safe
  "MongoClient opened before fork. Create MongoClient only "
                                                           ok
add 1 pilot(s)                                                                ok
Update: pipeline.0000.stage.0000.my-first-task state: SUBMITTING
submit 1 unit(s)
        .                                                                     ok
Update: pipeline.0000.stage.0000.my-first-task state: EXECUTED
Update: pipeline.0000.stage.0000.my-first-task state: DONE
Update: pipeline.0000.stage.0000 state: DONE
```
umgr.0000.log
```
1576126925.955 : umgr.0000            : 103727 : 140735785267632 : INFO     : [Callback]: unit unit.000000 state: UMGR_STAGING_OUTPUT.
1576126925.955 : umgr.0000            : 103727 : 140735785267632 : DEBUG    : umgr.0000 calls state cb unit_state_cb for unit.000000
1576126925.955 : umgr.0000            : 103727 : 140735785267632 : DEBUG    : unit.000000 calls state cb <bound method ComputeUnit._default_state_cb of {'type': 'unit', 'umgr': 'umgr.0000', 'uid': 'unit.000000', 'name': 'task.0000,my-first-task,stage.0000,None,pipeline.0000,None', 'state': 'DONE', 'exit_code': 0, 's
tdout': 'Thu Dec 12 00:02:01 EST 2019\n', 'stderr': '', 'pilot': 'pilot.0000', 'resource_sandbox': 'file://localhost/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox', 'pilot_sandbox': 'file://localhost/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/re.session.login2.hrlee.018242.0031/pilot.0000/', 'un
it_sandbox': 'file://localhost/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/re.session.login2.hrlee.018242.0031/pilot.0000/unit.000000/', 'client_sandbox': 'None', 'description': {'arguments': [], 'cleanup': False, 'cpu_process_type': '', 'cpu_processes': 1, 'cpu_thread_type': 'OpenMP', 'cpu_threads': 4, '
environment': {}, 'executable': '/bin/date', 'gpu_process_type': '', 'gpu_processes': 1, 'gpu_thread_type': 'CUDA', 'gpu_threads': 1, 'input_staging': [], 'kernel': '', 'lfs_per_process': 0, 'mem_per_process': 0, 'metadata': None, 'name': 'task.0000,my-first-task,stage.0000,None,pipeline.0000,None', 'output_staging'
: [], 'pilot': '', 'post_exec': [], 'pre_exec': [], 'restartable': False, 'sandbox': None, 'stderr': '', 'stdout': '', 'tags': {}}}>
1576126925.955 : umgr.0000            : 103727 : 140735785267632 : INFO     : [Callback]: unit unit.000000 state: DONE.
1576126925.955 : umgr.0000            : 103727 : 140735785267632 : DEBUG    : umgr.0000 calls state cb unit_state_cb for unit.000000
1576126927.371 : umgr.0000            : 103727 : 140735810630064 : INFO     : units pulled:    0
1576126928.489 : umgr.0000            : 103727 : 140735810630064 : INFO     : units pulled:    0
```

radical.log
```
1576128075.995 : umgr_staging_output.0000 : 112111 : 140735621755312 : DEBUG    : advance bulk: 1 [True, True]
1576128075.995 : state_pubsub         : 108999 : 140735983382960 : DEBUG    : <> state_pubsub: b'state_pubsub \x82\xa3cmd\xa6update\xa3arg\x91\x83\xa3uid\xabunit.000000\xa4type\xa4unit\xa5state\xb3UMGR_STAGING_OUTPUT'
1576128075.995 : umgr_staging_output.0000 : 112111 : 140735621755312 : DEBUG    : -> state_pubsub: {'cmd': 'update', 'arg': [{'_id': 'unit.000000', 'type': 'unit', 'umgr': 'umgr.0000', 'uid': 'unit.000000', 'name': 'task.0000,my-first-task,stage.0000,None,pipeline.0000,None', 'state': 'DONE', 'exit_code': 0, 'stdout': 'Thu Dec 12 00:21:13 EST 2019\n', 'stderr': '', 'pilot': 'pilot.0000', 'resource_sandbox': 'file://localhost/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox', 'pilot_sandbox': 'file://localhost/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/re.session.login2.hrlee.018242.0032/pilot.0000/', 'unit_sandbox': 'file://localhost/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/re.session.login2.hrlee.018242.0032/pilot.0000/unit.000000/', 'client_sandbox': 'None', 'description': {'arguments': [], 'cleanup': False, 'cpu_process_type': '', 'cpu_processes': 1, 'cpu_thread_type': 'OpenMP', 'cpu_threads': 4, 'environment': {}, 'executable': '/bin/date', 'gpu_process_type': '', 'gpu_processes': 1, 'gpu_thread_type': 'CUDA', 'gpu_threads': 1, 'input_staging': [], 'kernel': '', 'lfs_per_process': 0, 'mem_per_process': 0, 'metadata': None, 'name': 'task.0000,my-first-task,stage.0000,None,pipeline.0000,None', 'output_staging': [], 'pilot': '', 'post_exec': [], 'pre_exec': [], 'restartable': False, 'sandbox': None, 'stderr': '', 'stdout': '', 'tags': {}}, 'control': None, 'states': ['NEW', 'UMGR_SCHEDULING_PENDING', 'UMGR_SCHEDULING', 'UMGR_STAGING_INPUT_PENDING', 'UMGR_STAGING_INPUT', 'AGENT_STAGING_INPUT_PENDING', 'AGENT_STAGING_INPUT', 'AGENT_SCHEDULING_PENDING', 'AGENT_SCHEDULING', 'AGENT_EXECUTING', 'AGENT_STAGING_OUTPUT_PENDING', 'AGENT_STAGING_OUTPUT', 'UMGR_STAGING_OUTPUT_PENDING'], 'cmd': [], 'unit_sandbox_path': '/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/re.session.login2.hrlee.018242.0032/pilot.0000/unit.000000/', 'tuple_size': [1, 4, 1, ''], 'slots': {'nodes': [{'uid': '1', 'name': 'a20n08', 'core_map': [[0, 1, 2, 3]], 'gpu_map': [[0]], 'lfs': {'size': 0, 'path': None}, 'mem': 0}], 'cores_per_node': 167, 'gpus_per_node': 6, 'lfs_per_node': {'path': None, 'size': 0}, 'mem_per_node': 0, 'lm_info': {}}, 'stdout_file': '/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/re.session.login2.hrlee.018242.0032/pilot.0000/unit.000000/STDOUT', 'stderr_file': '/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/re.session.login2.hrlee.018242.0032/pilot.0000/unit.000000/STDERR', 'target_state': 'DONE'}]}
1576128075.995 : umgr_staging_output.0000 : 112111 : 140735621755312 : DEBUG    : -> state_pubsub: ?
1576128075.995 : umgr_scheduling.0000 : 111889 : 140735315505584 : DEBUG    : get state_pubsub [2]
1576128075.995 : umgr_scheduling.0000 : 111889 : 140735315505584 : INFO     : scheduler state_cb: update
1576128075.995 : umgr_staging_output.0000 : 112111 : 140735621755312 : DEBUG    : -> state_pubsub: [{'_id': 'unit.000000', 'type':
1576128075.995 : umgr_scheduling.0000 : 111889 : 140735315505584 : DEBUG    : update pilots []
1576128075.995 : umgr_scheduling.0000 : 111889 : 140735315505584 : DEBUG    : update units  ['unit.000000']
1576128075.995 : umgr_scheduling.0000 : 111889 : 140735315505584 : DEBUG    : update pilot states for []
1576128075.995 : umgr_staging_output.0000 : 112111 : 140735621755312 : DEBUG    : -> umgr_staging_output_queue [True ]: ?
1576128075.996 : state_pubsub         : 108999 : 140735983382960 : DEBUG    : <> state_pubsub: b'state_pubsub \x82\xa3cmd\xa6update\xa3arg\x91\xde\x00\x18\xa3_id\xabunit.000000\xa4type\xa4unit\xa4umgr\xa9umgr.0000\xa3uid\xabunit.000000\xa4name\xda\x00:task.0000,my-first-task,stage.0000,None,pipeline.0000,None\xa5state\xa4DONE\xa9exit_code\x00\xa6stdout\xbdThu Dec 12 00:21:13 EST 2019\n\xa6stderr\xa0\xa5pilot\xaapilot.0000\xb0resource_sandbox\xda\x00Gfile://localhost/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox\xadpilot_sandbox\xda\x00wfile://localhost/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/re.session.login2.hrlee.018242.0032/pilot.0000/\xacunit_sandbox\xda\x00\x83file://localhost/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/re.session.login2.hrlee.018242.0032/pilot.0000/unit.000000/\xaeclient_sandbox\xa4None\xabdescription\xde\x00\x1b\xa9arguments\x90\xa7cleanup\xc2\xb0cpu_process_type\xa0\xadcpu_processes\x01\xafcpu_thread_type\xa6OpenMP\xabcpu_threads\x04\xabenvironment\x80\xaaexecutable\xa9/bin/date\xb0gpu_process_type\xa0\xadgpu_processes\x01\xafgpu_thread_type\xa4CUDA\xabgpu_threads\x01\xadinput_staging\x90\xa6kernel\xa0\xaflfs_per_process\x00\xafmem_per_process\x00\xa8metadata\xc0\xa4name\xda\x00:task.0000,my-first-task,stage.0000,None,pipeline.0000,None\xaeoutput_staging\x90\xa5pilot\xa0\xa9post_exec\x90\xa8pre_exec\x90\xabrestartable\xc2\xa7sandbox\xc0\xa6stderr\xa0\xa6stdout\xa0\xa4tags\x80\xa7control\xc0\xa6states\x9d\xa3NEW\xb7UMGR_SCHEDULING_PENDING\xafUMGR_SCHEDULING\xbaUMGR_STAGING_INPUT_PENDING\xb2UMGR_STAGING_INPUT\xbbAGENT_STAGING_INPUT_PENDING\xb3AGENT_STAGING_INPUT\xb8AGENT_SCHEDULING_PENDING\xb0AGENT_SCHEDULING\xafAGENT_EXECUTING\xbcAGENT_STAGING_OUTPUT_PENDING\xb4AGENT_STAGING_OUTPUT\xbbUMGR_STAGING_OUTPUT_PENDING\xa3cmd\x90\xb1unit_sandbox_path\xda\x00s/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/re.session.login2.hrlee.018242.0032/pilot.0000/unit.000000/\xaatuple_size\x94\x01\x04\x01\xa0\xa5slots\x86\xa5nodes\x91\x86\xa3uid\xa11\xa4name\xa6a20n08\xa8core_map\x91\x94\x00\x01\x02\x03\xa7gpu_map\x91\x91\x00\xa3lfs\x82\xa4size\x00\xa4path\xc0\xa3mem\x00\xaecores_per_node\xcc\xa7\xadgpus_per_node\x06\xaclfs_per_node\x82\xa4path\xc0\xa4size\x00\xacmem_per_node\x00\xa7lm_info\x80\xabstdout_file\xda\x00y/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/re.session.login2.hrlee.018242.0032/pilot.0000/unit.000000/STDOUT\xabstderr_file\xda\x00y/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/re.session.login2.hrlee.018242.0032/pilot.0000/unit.000000/STDERR\xactarget_state\xa4DONE'
1576128075.996 : umgr_staging_output.0000 : 112111 : 140735621755312 : DEBUG    : -> umgr_staging_output_queue [True ]: request 112111
1576128075.996 : umgr_scheduling.0000 : 111889 : 140735315505584 : DEBUG    : get state_pubsub [2]
1576128075.996 : umgr_scheduling.0000 : 111889 : 140735315505584 : INFO     : scheduler state_cb: update
1576128075.996 : umgr_scheduling.0000 : 111889 : 140735315505584 : DEBUG    : update pilots []
1576128075.996 : umgr_scheduling.0000 : 111889 : 140735315505584 : DEBUG    : update units  ['unit.000000']
1576128075.996 : umgr_scheduling.0000 : 111889 : 140735315505584 : DEBUG    : update pilot states for []
```

pmgr.0000.log
```
1576128076.008 : pmgr.0000            : 108833 : 140734200017328 : DEBUG    : get state_pubsub [2]
1576128076.008 : pmgr.0000            : 108833 : 140734200017328 : DEBUG    : state event: {'cmd': 'update', 'arg': [{'_id': 'unit.000000', 'type': 'unit', 'umgr': 'umgr.0000', 'uid': 'unit.000000', 'name': 'task.0000,my-first-task,stage.0000,None,pipeline.0000,None', 'state': 'DONE', 'exit_code': 0, 'stdout': 'Thu
Dec 12 00:21:13 EST 2019\n', 'stderr': '', 'pilot': 'pilot.0000', 'resource_sandbox': 'file://localhost/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox', 'pilot_sandbox': 'file://localhost/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/re.session.login2.hrlee.018242.0032/pilot.0000/', 'unit_sandbox':
'file://localhost/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/re.session.login2.hrlee.018242.0032/pilot.0000/unit.000000/', 'client_sandbox': 'None', 'description': {'arguments': [], 'cleanup': False, 'cpu_process_type': '', 'cpu_processes': 1, 'cpu_thread_type': 'OpenMP', 'cpu_threads': 4, 'environment':
 {}, 'executable': '/bin/date', 'gpu_process_type': '', 'gpu_processes': 1, 'gpu_thread_type': 'CUDA', 'gpu_threads': 1, 'input_staging': [], 'kernel': '', 'lfs_per_process': 0, 'mem_per_process': 0, 'metadata': None, 'name': 'task.0000,my-first-task,stage.0000,None,pipeline.0000,None', 'output_staging': [], 'pilot'
: '', 'post_exec': [], 'pre_exec': [], 'restartable': False, 'sandbox': None, 'stderr': '', 'stdout': '', 'tags': {}}, 'control': None, 'states': ['NEW', 'UMGR_SCHEDULING_PENDING', 'UMGR_SCHEDULING', 'UMGR_STAGING_INPUT_PENDING', 'UMGR_STAGING_INPUT', 'AGENT_STAGING_INPUT_PENDING', 'AGENT_STAGING_INPUT', 'AGENT_SCHE
DULING_PENDING', 'AGENT_SCHEDULING', 'AGENT_EXECUTING', 'AGENT_STAGING_OUTPUT_PENDING', 'AGENT_STAGING_OUTPUT', 'UMGR_STAGING_OUTPUT_PENDING'], 'cmd': [], 'unit_sandbox_path': '/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/re.session.login2.hrlee.018242.0032/pilot.0000/unit.000000/', 'tuple_size': [1, 4, 1
, ''], 'slots': {'nodes': [{'uid': '1', 'name': 'a20n08', 'core_map': [[0, 1, 2, 3]], 'gpu_map': [[0]], 'lfs': {'size': 0, 'path': None}, 'mem': 0}], 'cores_per_node': 167, 'gpus_per_node': 6, 'lfs_per_node': {'path': None, 'size': 0}, 'mem_per_node': 0, 'lm_info': {}}, 'stdout_file': '/gpfs/alpine/scratch/hrlee/csc
393/radical.pilot.sandbox/re.session.login2.hrlee.018242.0032/pilot.0000/unit.000000/STDOUT', 'stderr_file': '/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/re.session.login2.hrlee.018242.0032/pilot.0000/unit.000000/STDERR', 'target_state': 'DONE'}]}
1576128079.831 : pmgr.0000            : 108833 : 140734577308080 : DEBUG    : ==== state pulled: pilot.0000: PMGR_ACTIVE
1576128089.962 : pmgr.0000            : 108833 : 140734577308080 : DEBUG    : ==== state pulled: pilot.0000: PMGR_ACTIVE
1576128100.103 : pmgr.0000            : 108833 : 140734577308080 : DEBUG    : ==== state pulled: pilot.0000: PMGR_ACTIVE

```
TMGR
```
]$ grep -i TMGR *
radical.entk.appmanager.0000.prof:1576128059.5625012,tmgr_create_start,radical.entk.appmanager.0000,MainThread,appmanager.0000,,
radical.entk.appmanager.0000.prof:1576128061.2016766,tmgr_create_stop,radical.entk.appmanager.0000,MainThread,appmanager.0000,,
radical.entk.task_manager.0000.prof:1576128060.9571741,tmgr_create,radical.entk.task_manager.0000,MainThread,task_manager.0000,,
radical.entk.task_manager.0000.prof:1576128060.9622998,creating tmgr process,radical.entk.task_manager.0000,MainThread,task_manager.0000,,
radical.entk.task_manager.0000.prof:1576128061.1112206,starting tmgr process,radical.entk.task_manager.0000,MainThread,task_manager.0000,,
radical.entk.task_manager.0000.prof:1576128061.1966991,tmgr process started,radical.entk.task_manager.0000,MainThread,task_manager.0000,,
radical.entk.task_manager.0000.prof:1576128062.0483744,tmgr infrastructure setup done,radical.entk.task_manager.0000,MainThread,task_manager.0000,,
```

**Comment by lee212** [comment]
Just a note, `python3/devel` can be removed once this PR is closed.

**Pull request closed without merging**
